name: CI - Trackly with Postgres

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: trackly
          POSTGRES_PASSWORD: trackly
          POSTGRES_DB: trackly_ci
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U trackly -d trackly_ci"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn -B clean install -Dspring.profiles.active=ci

      - name: Run tests
        run: mvn test -Dspring.profiles.active=ci -Dtest=TracklyAppApplicationTests

